openai:
  api_key:
  engine: gpt-3.5-turbo-instruct

database:
  host: localhost
  port: 5432
  user: myuser
  password: <<YOUR_PASSWORD>>
  database: mydatabase

environment:
  env: prod # Possible [ local, prod ]